IMAGE_NAME = "bento/ubuntu-20.04"

VM_GROUP_NAME = "vue-fastapi-devops"

# Network Configure
NETWORK_SUB = "192.168.50."
START_IP = 150

# VM Spec
spec = { :cpus => 2, :mem => 4096 }

Vagrant.configure("2") do |config|
  # vagrant configure
  config.vm.box = IMAGE_NAME
  config.vm.synced_folder "./backup", "/root/backup"

  # Development Server
  config.vm.define "dev", primary: true do |dev|
	dev.vm.box = IMAGE_NAME
	dev.vm.network "private_network", ip: "#{NETWORK_SUB}#{START_IP}"
	dev.vm.network "public_network"
	dev.vm.hostname = "dev"
	# dev.vm.provision "shell", path: "./scripts/python_install.sh"
	# dev.vm.provision "shell", path: "./scripts/docker_install.sh"
	# dev.vm.provision "shell", path: "./scripts/git_clone.sh", privileged: true
	
	dev.vm.provision "shell", path: "./scripts/ansible_install.sh"
	
	# file provision은 상승된 권한이 없다. $HOME = /home/vagrant
	dev.vm.provision "file", source: "./scripts/python_install.yml", destination: "$HOME/ansible-playbook/python_install.yml"
	dev.vm.provision "file", source: "./scripts/docker_install.yml", destination: "$HOME/ansible-playbook/docker_install.yml"
	dev.vm.provision "file", source: "./scripts/git_clone.yml", destination: "$HOME/ansible-playbook/git_clone.yml"
	dev.vm.provision "file", source: "./scripts/backup_source_code_with_cron.yml", destination: "$HOME/ansible-playbook/backup_source_code_with_cron.yml"
	dev.vm.provision "file", source: "./scripts/server_config.yml", destination: "$HOME/ansible-playbook/server_config.yml"
	
	# shell provision은 상승된 권한으로 실행된다. $HOME = /root
	dev.vm.provision "shell", inline: "ansible-playbook /home/vagrant/ansible-playbook/python_install.yml"
	dev.vm.provision "shell", inline: "ansible-playbook /home/vagrant/ansible-playbook/docker_install.yml"
	dev.vm.provision "shell", inline: "ansible-playbook /home/vagrant/ansible-playbook/git_clone.yml"
	dev.vm.provision "shell", inline: "ansible-playbook /home/vagrant/ansible-playbook/backup_source_code_with_cron.yml"
	dev.vm.provision "shell", inline: "ansible-playbook /home/vagrant/ansible-playbook/server_config.yml"
	dev.vm.provision "shell", path: "./scripts/nodejs_install.sh"

	dev.vm.provider "virtualbox" do |v|
	  v.name = "#{VM_GROUP_NAME}-dev"
	  v.gui = false
	  v.memory = spec[:mem]
	  v.cpus = spec[:cpus]
	  v.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
	end
  end
  
  # Product Server
    config.vm.define "pro", primary: true do |pro|
	pro.vm.box = IMAGE_NAME
	pro.vm.network "private_network", ip: "#{NETWORK_SUB}#{START_IP + 1}"
	pro.vm.hostname = "pro"
	pro.vm.provision "shell", path: "./scripts/python_install.sh"
	pro.vm.provision "shell", path: "./scripts/nodejs_install.sh"
	pro.vm.provision "shell", path: "./scripts/docker_install.sh"
  
	pro.vm.provider "virtualbox" do |v|
	  v.name = "#{VM_GROUP_NAME}-pro"
	  v.gui = false
	  v.memory = spec[:mem]
	  v.cpus = spec[:cpus]
	  v.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
	end
  end
end
